# Dados do banco
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_gerenciamento
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties.hibernate.format_sql: true
  mvc:
    converters:
      preferred-json-mapper: jackson